### ISSUE TITLE
When using image with name that matches computer name I get errors

### ISSUE THREAD

**Issue by formicsapien** [mdovgialo/OpenVRSharedPlayspace#2]
I get the following output when I renamed the image to the one the app is looking for for the connected computer.  When I put the name of the image back to default.png it works fine.

```
Found it!
Traceback (most recent call last):
  File "OpenVRSharedPlayspace.py", line 5, in <module>
    openvr_shared_playspace.main()
  File "C:\Programs\Open VR Shared Playspace\OpenVRSharedPlayspaceDist\openvr_shared_playspace\__init__.py", line 344, in main
    app.run()
  File "C:\Programs\Open VR Shared Playspace\OpenVRSharedPlayspaceDist\openvr_shared_playspace\__init__.py", line 289, in run
    self._draw(headset_id)
  File "C:\Programs\Open VR Shared Playspace\OpenVRSharedPlayspaceDist\openvr_shared_playspace\__init__.py", line 321, in _draw
    self._device_visualisers[name] = DeviceVisualiser(name)
  File "C:\Programs\Open VR Shared Playspace\OpenVRSharedPlayspaceDist\openvr_shared_playspace\__init__.py", line 154, in __init__
    self._image_file = self._image_file
AttributeError: 'DeviceVisualiser' object has no attribute '_image_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenVRSharedPlayspace.py", line 6, in <module>
    except (Exception, openvr.OpenVRError) as e:
NameError: name 'openvr' is not defined
```

I know this doesn't go here, but I thought you'ld like to know that I did not have to have an identical chaperone file for my two systems for this to work (though I'm sure they're very similar).

**Comment by mdovgialo** [comment]
@formicsapien 
Thanks for the traceback, it should be fixed in the 0.0.1a release, available NOW!

About chaperone: thank you for the info, it should be completely chaperone independent, but I'm still not sure, as one of my friends had a problem with it not being aligned properly.
